name: Workflow to use the output

on:
    workflow_dispatch:
    push:
        branches: [ main ]

jobs:
    print_messages:
        uses: ./.github/workflows/action.yml
        with:
            name: "Construyendo el futuro"
            

        
